In [4]:
import pandas as pd
import os
from os import walk

import skimage
from skimage import io

In [13]:
mypath = "/media/Store/juan/Datasets/VOC 2012/VOCdevkit/VOC2012/JPEGImages"

res = []
for (root, dirnames, files) in walk(mypath):
    if len(files) > 0:
        res.extend(list(zip([root]*len(files), files)))

df = pd.DataFrame(res, columns=['Path', 'File_Name'])

df = df[(df['File_Name'].str.contains("jpg"))]

print(df.describe())
df.head()

                                                     Path        File_Name
count                                               33260            33260
unique                                                  1            33260
top     /media/Store/juan/Datasets/VOC 2012/VOCdevkit/...  2008_007045.jpg
freq                                                33260                1

                                                Path        File_Name
0  /media/Store/juan/Datasets/VOC 2012/VOCdevkit/...  2011_006041.jpg
1  /media/Store/juan/Datasets/VOC 2012/VOCdevkit/...  2008_008382.jpg
2  /media/Store/juan/Datasets/VOC 2012/VOCdevkit/...  2008_006438.jpg
3  /media/Store/juan/Datasets/VOC 2012/VOCdevkit/...  2010_000972.jpg
4  /media/Store/juan/Datasets/VOC 2012/VOCdevkit/...  2010_002307.jpg

In [18]:
dataset = df.copy()

# Read image size

dataset['Size'] = dataset.apply(lambda row: os.path.join(row.Path, row.File_Name), axis=1)

dataset['Size'] = dataset.apply(lambda row: skimage.io.imread(row['Size']).shape, axis=1)

dataset[['high','width', 'channels']] = dataset['Size'].apply(pd.Series)

dataset.head()

,Path,File_Name,Size,high,width,channels
0,/media/Store/juan/Datasets/VOC 2012/VOCdevkit/...,2011_006041.jpg,"(334, 500, 3)",334,500,3
1,/media/Store/juan/Datasets/VOC 2012/VOCdevkit/...,2008_008382.jpg,"(375, 500, 3)",375,500,3
2,/media/Store/juan/Datasets/VOC 2012/VOCdevkit/...,2008_006438.jpg,"(369, 500, 3)",369,500,3
3,/media/Store/juan/Datasets/VOC 2012/VOCdevkit/...,2010_000972.jpg,"(500, 375, 3)",500,375,3
4,/media/Store/juan/Datasets/VOC 2012/VOCdevkit/...,2010_002307.jpg,"(449, 500, 3)",449,500,3

In [19]:

dataset.describe()

               high         width  channels
count  33260.000000  33260.000000   33260.0
mean     389.663169    466.480036       3.0
std       65.371557     62.127235       0.0
min       71.000000    142.000000       3.0
25%      338.000000    486.000000       3.0
50%      375.000000    500.000000       3.0
75%      400.000000    500.000000       3.0
max      500.000000    500.000000       3.0

In [28]:
dataset[(dataset['high'] * dataset['high']) < 10000]

,Path,File_Name,Size,high,width,channels
5360,/media/Store/juan/Datasets/VOC 2012/VOCdevkit/...,2008_003374.jpg,"(88, 400, 3)",88,400,3
24136,/media/Store/juan/Datasets/VOC 2012/VOCdevkit/...,2008_001823.jpg,"(71, 500, 3)",71,500,3